import { Router } from 'express';
import { CompanyAuthController } from '../controllers/companyAuthController';
import { chatUpload, fetchAttachmentUrl, downloadAttachment } from '../controllers/chatUploadController';
import { authenticate } from '../middlewares/authMiddleware';
import { authorizeRoles } from '../middlewares/rbacMiddleware';
import { enforceTenant } from '../middlewares/tenantMiddleware';
import { enforceEmployeeLoginEnabled } from '../middlewares/companySettingsMiddleware';
import { companyLoginValidation, createEmployeeValidation, updateEmployeeValidation, createGroupValidation, updateGroupValidation, postMessageValidation, leadValidation, updateLeadValidation, saleValidation, markSaleFailedValidation, createLeaveValidation } from '../validators/companyValidator';
import { createRemoteSupportValidation, updateRemoteSupportValidation } from '../validators/remoteSupportValidator';
import { createProjectValidation, updateProjectValidation } from '../validators/projectValidator';
import { CompanySalesController } from '../controllers/companySales.controller';
import { Roles } from '../constants/index';
import { AttendanceController } from '../controllers/attendanceController';
import { AnnouncementController } from '../controllers/announcementController';
import { LeaveController } from '../controllers/leaveController';
import { NotificationController } from '../controllers/notificationController';
import { CompanySettingsController } from '../controllers/companySettingsController';
import { RemoteSupportController } from '../controllers/remoteSupportController';
import { ProjectController } from '../controllers/projectController';
import { routePermission } from '../middlewares/routePermissionMiddleware';

const router = Router();

router.post('/login', companyLoginValidation, CompanyAuthController.login);
router.get('/validate', authenticate, enforceTenant, CompanyAuthController.validateSession);

router.use(authenticate, enforceTenant, enforceEmployeeLoginEnabled);
router.post('/logout', CompanyAuthController.logout);

router.get('/dashboard', authorizeRoles(Roles.COMPANY_ADMIN, Roles.HR, Roles.MANAGER, Roles.TEAM_LEAD, Roles.EMPLOYEE, Roles.SALES, Roles.TECH_SUPPORT, Roles.VERIFICATION, Roles.FEEDBACK, Roles.IT, Roles.INTERN), CompanyAuthController.getDashboard);
const companyEmployeeRoles = [Roles.COMPANY_ADMIN, Roles.HR, Roles.MANAGER, Roles.TEAM_LEAD, Roles.EMPLOYEE, Roles.SALES, Roles.TECH_SUPPORT, Roles.VERIFICATION, Roles.FEEDBACK, Roles.IT, Roles.INTERN] as const;

router.get('/attendance', authorizeRoles(...companyEmployeeRoles), routePermission('attendance'), AttendanceController.list);
router.get('/attendance/employees', authorizeRoles(Roles.COMPANY_ADMIN), AttendanceController.employees);
router.get('/announcements', authorizeRoles(...companyEmployeeRoles), routePermission('announcements'), AnnouncementController.list);
router.post('/announcements', authorizeRoles(Roles.COMPANY_ADMIN), AnnouncementController.create);
router.patch('/announcements/:id/read', authorizeRoles(...companyEmployeeRoles), routePermission('announcements'), AnnouncementController.markRead);
router.delete('/announcements/:id', authorizeRoles(Roles.COMPANY_ADMIN), AnnouncementController.remove);
router.get('/leave', authorizeRoles(...companyEmployeeRoles), routePermission('leave'), LeaveController.list);
router.post('/leave', authorizeRoles(...companyEmployeeRoles), routePermission('leave'), createLeaveValidation, LeaveController.create);
router.patch('/leave/:id/status', authorizeRoles(Roles.COMPANY_ADMIN), LeaveController.updateStatus);
router.get('/settings', authorizeRoles(...companyEmployeeRoles), CompanySettingsController.getSettings);
router.patch('/theme', authorizeRoles(...companyEmployeeRoles), CompanyAuthController.updateTheme);
router.patch('/settings', authorizeRoles(Roles.COMPANY_ADMIN), CompanySettingsController.updateSettings);
router.get('/settings/holidays', authorizeRoles(Roles.COMPANY_ADMIN), CompanySettingsController.listHolidays);
router.post('/settings/holidays', authorizeRoles(Roles.COMPANY_ADMIN), CompanySettingsController.addHoliday);
router.patch('/settings/holidays/:hid', authorizeRoles(Roles.COMPANY_ADMIN), CompanySettingsController.updateHoliday);
router.delete('/settings/holidays/:hid', authorizeRoles(Roles.COMPANY_ADMIN), CompanySettingsController.deleteHoliday);
router.get('/notifications', authorizeRoles(...companyEmployeeRoles), routePermission('notifications'), NotificationController.list);
router.patch('/notifications/:id/read', authorizeRoles(...companyEmployeeRoles), routePermission('notifications'), NotificationController.markRead);
router.get('/employees', authorizeRoles(Roles.COMPANY_ADMIN), CompanyAuthController.getEmployees);
router.post('/employees', authorizeRoles(Roles.COMPANY_ADMIN), createEmployeeValidation, CompanyAuthController.createEmployee);
router.patch('/employees/:id', authorizeRoles(Roles.COMPANY_ADMIN), updateEmployeeValidation, CompanyAuthController.updateEmployee);
router.patch('/employees/:id/status', authorizeRoles(Roles.COMPANY_ADMIN), CompanyAuthController.updateEmployeeStatus);
router.delete('/employees/:id', authorizeRoles(Roles.COMPANY_ADMIN), CompanyAuthController.deleteEmployee);
router.patch('/employees/:id/permissions', authorizeRoles(Roles.COMPANY_ADMIN), CompanyAuthController.updateEmployeePermissions);
router.get('/leads', authorizeRoles(...companyEmployeeRoles), routePermission('leads'), CompanySalesController.getLeads);
router.post('/leads', authorizeRoles(...companyEmployeeRoles), routePermission('leads'), leadValidation, CompanySalesController.createLead);
router.post('/leads/:id/accept', authorizeRoles(...companyEmployeeRoles), routePermission('leads'), CompanySalesController.acceptLead);
router.patch('/leads/:id', authorizeRoles(...companyEmployeeRoles), routePermission('leads'), updateLeadValidation, CompanySalesController.updateLead);
router.delete('/leads/:id', authorizeRoles(Roles.COMPANY_ADMIN), CompanySalesController.deleteLead);
router.get('/sales', authorizeRoles(...companyEmployeeRoles), routePermission('sales'), CompanySalesController.getSales);
router.get('/sales/customers/search', authorizeRoles(...companyEmployeeRoles), routePermission('sales'), CompanySalesController.searchCustomers);
router.post('/sales', authorizeRoles(...companyEmployeeRoles), routePermission('sales'), saleValidation, CompanySalesController.createSale);
router.post('/sales/upgrades', authorizeRoles(...companyEmployeeRoles), routePermission('sales'), CompanySalesController.createUpgrade);
router.get('/sales/upgrades', authorizeRoles(...companyEmployeeRoles), routePermission('sales'), CompanySalesController.getUpgrades);
router.patch('/sales/:id', authorizeRoles(...companyEmployeeRoles), routePermission('sales'), saleValidation, CompanySalesController.updateSale);
router.patch('/sales/:id/failed', authorizeRoles(Roles.COMPANY_ADMIN), markSaleFailedValidation, CompanySalesController.markSaleFailed);
router.delete('/sales/:id', authorizeRoles(Roles.COMPANY_ADMIN), CompanySalesController.deleteSale);

router.get('/verification', authorizeRoles(...companyEmployeeRoles), routePermission('verification'), CompanySalesController.getVerifications);
router.post('/verification', authorizeRoles(Roles.COMPANY_ADMIN, Roles.MANAGER, Roles.VERIFICATION), routePermission('verification'), saleValidation, CompanySalesController.createVerification);
router.patch('/verification/:id', authorizeRoles(Roles.COMPANY_ADMIN, Roles.MANAGER, Roles.VERIFICATION), routePermission('verification'), saleValidation, CompanySalesController.updateVerification);
router.delete('/verification/:id', authorizeRoles(Roles.COMPANY_ADMIN, Roles.MANAGER, Roles.VERIFICATION), routePermission('verification'), CompanySalesController.deleteVerification);
router.post('/verification/:id/start', authorizeRoles(...companyEmployeeRoles), routePermission('verification'), CompanySalesController.startVerification);
router.post('/verification/:id/complete', authorizeRoles(...companyEmployeeRoles), routePermission('verification'), CompanySalesController.completeVerification);

router.get('/feedback', authorizeRoles(...companyEmployeeRoles), routePermission('feedback'), CompanySalesController.getFeedbacks);
router.post('/feedback/:id/complete', authorizeRoles(...companyEmployeeRoles), routePermission('feedback'), CompanySalesController.completeFeedback);

router.get('/todays-work', authorizeRoles(...companyEmployeeRoles), CompanySalesController.getTodaysWork);
router.get('/remote-support', authorizeRoles(...companyEmployeeRoles), routePermission('remote-support'), RemoteSupportController.list);
router.post('/remote-support', authorizeRoles(...companyEmployeeRoles), routePermission('remote-support'), RemoteSupportController.create);
router.post('/remote-support/:id/accept', authorizeRoles(...companyEmployeeRoles), routePermission('remote-support'), RemoteSupportController.accept);
router.post('/remote-support/:id/reject', authorizeRoles(...companyEmployeeRoles), routePermission('remote-support'), RemoteSupportController.reject);
router.post('/remote-support/:id/complete', authorizeRoles(...companyEmployeeRoles), routePermission('remote-support'), RemoteSupportController.complete);
router.post('/remote-support/:id/assign', authorizeRoles(Roles.COMPANY_ADMIN, Roles.MANAGER), routePermission('remote-support'), RemoteSupportController.assign);
router.patch('/remote-support/:id', authorizeRoles(...companyEmployeeRoles), routePermission('remote-support'), RemoteSupportController.update);
router.delete('/remote-support/:id', authorizeRoles(...companyEmployeeRoles), routePermission('remote-support'), RemoteSupportController.delete);
router.get('/projects', authorizeRoles(...companyEmployeeRoles), routePermission('projects'), ProjectController.list);
router.post('/projects', authorizeRoles(Roles.COMPANY_ADMIN, Roles.IT), routePermission('projects'), createProjectValidation, ProjectController.create);
router.patch('/projects/:id', authorizeRoles(Roles.COMPANY_ADMIN, Roles.IT), routePermission('projects'), updateProjectValidation, ProjectController.update);
router.post('/groups', authorizeRoles(Roles.COMPANY_ADMIN), createGroupValidation, CompanyAuthController.createGroup);
router.patch('/groups/:groupId', authorizeRoles(Roles.COMPANY_ADMIN), updateGroupValidation, CompanyAuthController.updateGroup);
router.delete('/groups/:groupId', authorizeRoles(Roles.COMPANY_ADMIN), CompanyAuthController.deleteGroup);
router.post('/groups/:groupId/messages', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), postMessageValidation, CompanyAuthController.postMessage);
router.get('/groups/:groupId/messages', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), CompanyAuthController.getGroupMessages);
router.get('/conversations/:conversationId/messages', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), CompanyAuthController.getConversationMessages);
router.post('/conversations/:conversationId/read', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), CompanyAuthController.markConversationRead);
router.post('/conversations/:conversationId/messages', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), postMessageValidation, CompanyAuthController.postConversationMessage);
router.post('/conversations/:conversationId/upload', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), chatUpload);
router.get('/conversations/:conversationId/messages/:messageId/attachment', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), fetchAttachmentUrl);
router.get('/conversations/:conversationId/messages/:messageId/download', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), downloadAttachment);
router.patch('/messages/:messageId', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), postMessageValidation, CompanyAuthController.updateMessage);
router.delete('/messages/:messageId', authorizeRoles(...companyEmployeeRoles), routePermission('chat'), CompanyAuthController.deleteMessage);

export default router;
